NIG = ['NGBON']
ABU = ['FI','DI']

CHARTER_BOIL_OFF = 0.0012 # Hardkodet 
TANK_LEFTOVER_VALUE={'NGBON':40} # Hardkodet
ALLOWED_WAITING = 7

CHARTER_VESSEL_UPPER_CAPACITY = 180000
CHARTER_VESSEL_LOWER_CAPACITY = 100000